new gpu-detector with --dry-run and --with-lspci support, moreover fixed Intel 830 detection
git-svn-id: http://svn.sabayonlinux.org/overlay@440 d7aec97c-591d-0410-af39-a8856400b30a

diff --git a/sys-apps/gpu-detector/files/gpu-configuration b/sys-apps/gpu-detector/files/gpu-configuration
--- a/sys-apps/gpu-detector/files/gpu-configuration
+++ b/sys-apps/gpu-detector/files/gpu-configuration
@@ -1,87 +1,114 @@
 #!/bin/sh
 
 XORGFILE="/etc/X11/xorg.conf"
+dry_run_detected=$(echo $@ | grep "dry-run")
+lspci_output=$(echo $@ | grep "with-lspci=")
+if [ -n "$lspci_output" ]; then
+    lspci_output=$(echo $@)
+else
+    lspci_output=$(lspci)
+fi
 
 remove_proprietary_opengl() {
-   # Fix for DRI accel
-   mount -t tmpfs none /usr/lib/opengl/ati &> /dev/null
-   mount -t tmpfs none /usr/lib/opengl/nvidia &> /dev/null
-   # FIX For fscking ATI env.d file
-   rm -f /etc/env.d/*ati &> /dev/null
-   sed -i '/LIBGL_DRIVERS_PATH s/.*//' /etc/profile.env
-   nice -20 source /etc/profile &> /dev/null
-   nice -20 eselect opengl set xorg-x11
+    if [ -z "$dry_run_detected" ]; then
+        # Fix for DRI accel
+        mount -t tmpfs none /usr/lib/opengl/ati &> /dev/null
+        mount -t tmpfs none /usr/lib/opengl/nvidia &> /dev/null
+        # FIX For fscking ATI env.d file
+        rm -f /etc/env.d/*ati &> /dev/null
+        sed -i '/LIBGL_DRIVERS_PATH s/.*//' /etc/profile.env
+        nice -20 source /etc/profile &> /dev/null
+        nice -20 eselect opengl set xorg-x11
+    else
+        echo "I was about to remove proprietary OpenGL libraries"
+    fi
 }
 
 change_xorg_driver() {
-    sed -i '/do not remove vesa/ s/".*"/"'$1'"/' $XORGFILE
+    if [ -z "$dry_run_detected" ]; then
+        sed -i '/do not remove vesa/ s/".*"/"'$1'"/' $XORGFILE
+    else
+        echo "I was about to change X.Org driver to: "$1
+    fi
 }
 
 enable_dri() {
-    sed -i '/"dri"/ s/#//' $XORGFILE
+    if [ -z "$dry_run_detected" ]; then
+        sed -i '/"dri"/ s/#//' $XORGFILE
+    else
+        echo "I was about to Enable DRI"
+    fi
 }
 
 fix_possible_opengl_misconfiguration() {
-
-    current_opengl_subsystem=$(eselect opengl show)
-    if [ "$1" = "ati" ]; then
-        if [ "$current_opengl_subsystem" != "ati" ]; then
-            # fix it!
-            nice -20 eselect opengl set ati
+    if [ -z "$dry_run_detected" ]; then
+        current_opengl_subsystem=$(eselect opengl show)
+        if [ "$1" = "ati" ]; then
+            if [ "$current_opengl_subsystem" != "ati" ]; then
+                # fix it!
+                nice -20 eselect opengl set ati
+            fi
         fi
-    fi
 
-    if [ "$1" = "nvidia" ]; then
-        if [ "$current_opengl_subsystem" != "nvidia" ]; then
-            # fix it!
-            nice -20 eselect opengl set nvidia
+        if [ "$1" = "nvidia" ]; then
+            if [ "$current_opengl_subsystem" != "nvidia" ]; then
+                # fix it!
+                nice -20 eselect opengl set nvidia
+            fi
         fi
+    else
+        echo "I was about to fix OpenGL subsystem to: "$1", while tue current implementation is "$current_opengl_subsystem
     fi
 
 }
 
-NEOMAGIC=$(lspci | grep ' VGA ' | grep -i 'neomagic')
-MACH64=$(lspci | grep ' VGA ' | grep -i 'mach64' )
-SAVAGE=$(lspci | grep ' VGA ' | grep -i 'savage' )
-VIRGE=$(lspci | grep ' VGA ' | grep -i 'Virge' )
-CYRIX=$(lspci | grep ' VGA ' | grep -i 'cyrix' )
-I128=$(lspci | grep ' VGA ' | grep -i 'i128' )
-I740=$(lspci | grep ' VGA ' | grep -iE ' intel.*74' )
-RENDITION=$(lspci | grep ' VGA ' | grep -i 'rendition' )
-SILICONMOTION=$(lspci | grep ' VGA ' | grep -iE ' silicon.*motion' )
-TSENG=$(lspci | grep ' VGA ' | grep -i 'tseng')
-IGRANTSDALE=$(lspci | grep ' VGA ' | grep -i "Intel Corp.*915.*")
-INTEL=$(lspci | grep ' VGA ' | grep -i "Intel Corp.*")
-I845=$(lspci | grep ' VGA ' | grep -i "Intel Corp.*845.*")
-I855=$(lspci | grep ' VGA ' | grep -i "Intel Corp.*855.*")
-V3DFX=$(lspci | grep ' VGA ' | grep -i "3Dfx Interactive" )
-I915=$(lspci | grep ' VGA ' | grep -i "Intel Corp.*915.*")
-I945=$(lspci | grep ' VGA ' |grep -i "Intel Corp.*945.*" || lspci | grep ' VGA ' | grep -i "Intel Corp.*940.*" )
-TRIDENT=$(lspci | grep ' VGA '  | grep Trident)
-NVIDIA=$(lspci | grep ' VGA ' | grep -i "nVidia")
-NVIDIATNT=$(lspci | grep ' VGA ' | grep -i "RIVA TNT")
-ATI=$(lspci | grep ' VGA ' | grep ATI)
-R7000=$(lspci | grep ' VGA ' | grep R100 || lspci | grep ' VGA ' | grep RV100 )
-R7200=$(lspci | grep ' VGA ' | grep -i "Radeon R100")
-R7500=$(lspci | grep ' VGA ' | grep -i "Radeon RV200")
-R2XX=$(lspci | grep ' VGA ' | grep -i "ATi Tech" |grep -i "RV2.*" || lspci | grep ' VGA ' | grep -i "ATi Tech" |grep -i "R2.*")
-R1XX=$(lspci | grep ' VGA ' | grep -i "ATi Tech" |grep -i "RV1.*" || lspci | grep ' VGA ' | grep -i "ATi Tech" |grep -i "R1.*")
-RX700=$(lspci | grep ' VGA ' | grep -i "Radeon Mobility X700")
-R9600=$(lspci | grep ' VGA ' | grep -i 'ATI Technologies .* RV350' )
-RAGE128=$(lspci | grep ' VGA ' | grep -i "Rage 128")
-SIS=$(lspci | grep ' VGA ' | grep -i "SiS")
-VMWARE=$(lspci | grep ' VGA ' | grep VMWare || lspci | grep ' VGA ' | grep VMware )
-VIRGE=$(lspci | grep ' VGA ' | grep -i "S3.*virge")
-VIA=$(lspci | grep ' VGA ' | grep -i "VIA Tech.*")
-MATROX=$(lspci | grep ' VGA ' | grep -i Matrox)
-CIRRUS=$(lspci | grep ' VGA ' | grep -i Cirrus)
+NEOMAGIC=$(echo $lspci_output | grep ' VGA ' | grep -i 'neomagic')
+MACH64=$(echo $lspci_output | grep ' VGA ' | grep -i 'mach64' )
+SAVAGE=$(echo $lspci_output | grep ' VGA ' | grep -i 'savage' )
+VIRGE=$(echo $lspci_output | grep ' VGA ' | grep -i 'Virge' )
+CYRIX=$(echo $lspci_output | grep ' VGA ' | grep -i 'cyrix' )
+I128=$(echo $lspci_output | grep ' VGA ' | grep -i 'i128' )
+I740=$(echo $lspci_output | grep ' VGA ' | grep -iE ' intel.*74' )
+RENDITION=$(echo $lspci_output | grep ' VGA ' | grep -i 'rendition' )
+SILICONMOTION=$(echo $lspci_output | grep ' VGA ' | grep -iE ' silicon.*motion' )
+TSENG=$(echo $lspci_output | grep ' VGA ' | grep -i 'tseng')
+IGRANTSDALE=$(echo $lspci_output | grep ' VGA ' | grep -i "Intel Corp.*915.*")
+INTEL=$(echo $lspci_output | grep ' VGA ' | grep -i "Intel Corp")
+I830=$(echo $lspci_output | grep ' VGA ' | grep -i "Intel Corp.*82830.*")
+I845=$(echo $lspci_output | grep ' VGA ' | grep -i "Intel Corp.*845.*")
+I855=$(echo $lspci_output | grep ' VGA ' | grep -i "Intel Corp.*855.*")
+V3DFX=$(echo $lspci_output | grep ' VGA ' | grep -i "3Dfx Interactive" )
+I915=$(echo $lspci_output | grep ' VGA ' | grep -i "Intel Corp.*915.*")
+I945=$(echo $lspci_output | grep ' VGA ' |grep -i "Intel Corp.*945.*" || echo $lspci_output | grep ' VGA ' | grep -i "Intel Corp.*940.*" )
+TRIDENT=$(echo $lspci_output | grep ' VGA '  | grep Trident)
+NVIDIA=$(echo $lspci_output | grep ' VGA ' | grep -i "nVidia")
+NVIDIATNT=$(echo $lspci_output | grep ' VGA ' | grep -i "RIVA TNT")
+ATI=$(echo $lspci_output | grep ' VGA ' | grep ATI)
+R7000=$(echo $lspci_output | grep ' VGA ' | grep R100 || echo $lspci_output | grep ' VGA ' | grep RV100 )
+R7200=$(echo $lspci_output | grep ' VGA ' | grep -i "Radeon R100")
+R7500=$(echo $lspci_output | grep ' VGA ' | grep -i "Radeon RV200")
+R2XX=$(echo $lspci_output | grep ' VGA ' | grep -i "ATi Tech" |grep -i "RV2.*" || echo $lspci_output | grep ' VGA ' | grep -i "ATi Tech" |grep -i "R2.*")
+R1XX=$(echo $lspci_output | grep ' VGA ' | grep -i "ATi Tech" |grep -i "RV1.*" || echo $lspci_output | grep ' VGA ' | grep -i "ATi Tech" |grep -i "R1.*")
+RX700=$(echo $lspci_output | grep ' VGA ' | grep -i "Radeon Mobility X700")
+R9600=$(echo $lspci_output | grep ' VGA ' | grep -i 'ATI Technologies .* RV350' )
+RAGE128=$(echo $lspci_output | grep ' VGA ' | grep -i "Rage 128")
+SIS=$(echo $lspci_output | grep ' VGA ' | grep -i "SiS")
+VMWARE=$(echo $lspci_output | grep ' VGA ' | grep VMWare || echo $lspci_output | grep ' VGA ' | grep VMware )
+VIRGE=$(echo $lspci_output | grep ' VGA ' | grep -i "S3.*virge")
+VIA=$(echo $lspci_output | grep ' VGA ' | grep -i "VIA Tech.*")
+MATROX=$(echo $lspci_output | grep ' VGA ' | grep -i Matrox)
+CIRRUS=$(echo $lspci_output | grep ' VGA ' | grep -i Cirrus)
 NOPROP=$(cat /proc/cmdline | grep "noproprietary")
 LEGACY=$(cat /proc/cmdline | grep "legacy")
 
 if [ -z "$ATI" ]; then
-    # FIX For fscking ATI env.d file
-    rm -f /etc/env.d/*ati &> /dev/null
-    env-update && source /etc/profile &> /dev/null
+    if [ -z "$dry_run_detected" ]; then
+        # FIX For fscking ATI env.d file
+        rm -f /etc/env.d/*ati &> /dev/null
+        env-update && source /etc/profile &> /dev/null
+    else
+        echo "ATI cards not detected, skipping env.d files removal"
+    fi
 fi
 
 current_arch=$(uname -m)
@@ -136,48 +163,52 @@ if [ -n "$NVIDIA" ]; then
      fi
      # Check for errors
      if [ "$nv_mod_failed" == "yes" ]; then
-         # ok, maybe unsupported
-         # check if we are running in the live mode
-         is_live=$(cat /proc/cmdline | grep cdroot)
-         if [ -n "$is_live" ]; then
-             # yes, so, check for the legacy drivers
-             if [ -e "/lib/modules/nvidia/legacy" ]; then
+         if [ -z "$dry_run_detected" ]; then
+             # ok, maybe unsupported
+             # check if we are running in the live mode
+             is_live=$(cat /proc/cmdline | grep cdroot)
+             if [ -n "$is_live" ]; then
+                 # yes, so, check for the legacy drivers
+                 if [ -e "/lib/modules/nvidia/legacy" ]; then
 
-                 # prepare legacy drivers
-                 if [ -e "/usr/bin/qlist" ]; then
-                     qlist -e nvidia-drivers | xargs rm -rf
-                     rm -rf /var/db/pkg/x11-drivers/nvidia-drivers-*
-                     sed -i '/.*nvidia-drivers.*/d' /var/lib/portage/world
+                     # prepare legacy drivers
+                     if [ -e "/usr/bin/qlist" ]; then
+                         qlist -e nvidia-drivers | xargs rm -rf
+                         rm -rf /var/db/pkg/x11-drivers/nvidia-drivers-*
+                         sed -i '/.*nvidia-drivers.*/d' /var/lib/portage/world
+                     else
+                         emerge -C nvidia-drivers &> /dev/null
+                     fi
+
+                     # remove old nvidia.ko
+                     rm /lib/modules/$(uname -r)/video/nvidia.ko -f
+                     # copy over
+                     cp /lib/nvidia/legacy/* / -Rp &> /dev/null
+                     # create nvidia.ko
+                     ld -m $ld_arch -r -o /lib/modules/$(uname -r)/video/nvidia.ko /lib/nvidia/legacy/nvidia.o /lib/nvidia/legacy/nvidia.mod.o
+                     # set nvidia
+                     nice -20 source /etc/profile
+                     nice -20 eselect opengl set nvidia &> /dev/null
+                     # hope that will work
+                     touch /lib/nvidia/legacy/running
+
+                     change_xorg_driver nvidia
+                     fix_possible_opengl_misconfiguration nvidia
+
                  else
-                     emerge -C nvidia-drivers &> /dev/null
+
+                     # revert to nv
+                     change_xorg_driver nv
+                     echo -e "\t Display Driver: NVIDIA (OpenSource) - Legacy drivers cannot be deployed"
+
                  fi
-
-                 # remove old nvidia.ko
-                 rm /lib/modules/$(uname -r)/video/nvidia.ko -f
-                 # copy over
-                 cp /lib/nvidia/legacy/* / -Rp &> /dev/null
-                 # create nvidia.ko
-                 ld -m $ld_arch -r -o /lib/modules/$(uname -r)/video/nvidia.ko /lib/nvidia/legacy/nvidia.o /lib/nvidia/legacy/nvidia.mod.o
-                 # set nvidia
-                 nice -20 source /etc/profile
-                 nice -20 eselect opengl set nvidia &> /dev/null
-                 # hope that will work
-                 touch /lib/nvidia/legacy/running
-
-                 change_xorg_driver nvidia
-                 fix_possible_opengl_misconfiguration nvidia
-
              else
-
                  # revert to nv
                  change_xorg_driver nv
-                 echo -e "\t Display Driver: NVIDIA (OpenSource) - Legacy drivers cannot be deployed"
-
+                 echo -e "\t Display Driver: NVIDIA (OpenSource) - Proprietary drivers can't be loaded - unsupported video card?"
              fi
          else
-             # revert to nv
-             change_xorg_driver nv
-             echo -e "\t Display Driver: NVIDIA (OpenSource) - Proprietary drivers can't be loaded - unsupported video card?"
+             echo "NVIDIA non-legacy drivers modprobe failed, I was about to try nvidia-legacy ones"
          fi
      else
        # ok, configure the standard nvidia driver
@@ -203,13 +234,21 @@ elif [ -n "$V3DFX" ]; then
     sed -i '/DefaultDepth/ s/24/16/' $XORGFILE
     echo -e "\t Display Driver: 3Dfx Video Card"
 
-elif [ -n "$I855" ] || [ -n "$I915" ] || [ -n "$I945" ] || [ -n "$I845" ] || [ -n "$IGRANTSDALE" ]; then
+elif [ -n "$I855" ] || [ -n "$I915" ] || [ -n "$I945" ] || [ -n "$I845" ] || [ -n "$IGRANTSDALE" ] || [ -n "$I830" ]; then
 
     change_xorg_driver i810
     enable_dri
     remove_proprietary_opengl
 
     echo -e "\t Display Driver: Intel Video Card"
+
+elif [ -n "$INTEL" ]; then
+
+    # unfortunately, I cannot detect the Intel card correctly, so I am trying to force i810 at least
+    change_xorg_driver i810
+    enable_dri
+    remove_proprietary_opengl
+    echo -e "\t Display Driver: Intel Video Card - not detected with precision, trying i810 driver"
 
 elif [ -n "$ATI" ] || [ -n "$RX700" ] || [ -n "$R9600" ]; then
 
